# Generated by Django 4.2.7 on 2024-01-12 04:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('second', '0004_alter_category_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='user',
        ),
    ]
